name: Run unit tests
on: [push]
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Check out code to the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        run: KNOWLEDGE_BASE="AAA" go test ./...
